// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.239
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ForumTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Forum Commenting")]
    [NUnit.Framework.CategoryAttribute("ForumAgentSpecs")]
    public partial class ForumCommentingFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ForumCommenting.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Forum Commenting", "In order to interact with a Forum\r\nAs a Forum User\r\nI want to create Posts in tha" +
                    "t Forum", ProgrammingLanguage.CSharp, new string[] {
                        "ForumAgentSpecs"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Comment on Post")]
        public virtual void CommentOnPost()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Comment on Post", ((string[])(null)));
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("the agent ForumAgent");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "Body",
                        "CategoryIdentifier",
                        "AuthorIdentifier",
                        "ForumIdentifier"});
            table1.AddRow(new string[] {
                        "Post Title",
                        "Post Body",
                        "11111111-1111-1111-1111-111111111111",
                        "00000000-0000-0000-0000-000000000000",
                        "33333333-3333-3333-3333-333333333333"});
#line 10
 testRunner.When("I publish the command PublishPost:", ((string)(null)), table1);
#line 13
 testRunner.And("the command is complete");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "Body",
                        "CategoryIdentifier",
                        "AuthorIdentifier",
                        "ForumIdentifier"});
            table2.AddRow(new string[] {
                        "Comment Title",
                        "Comment Body",
                        "11111111-1111-1111-1111-111111111111",
                        "00000000-0000-0000-0000-000000000000",
                        "33333333-3333-3333-3333-333333333333"});
#line 15
 testRunner.When("I publish the command CommentOnPost:", ((string)(null)), table2);
#line 18
 testRunner.And("the command is complete");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title"});
            table3.AddRow(new string[] {
                        "Post Title"});
#line 20
 testRunner.Then("run FindByTitle on PostQueries with:", ((string)(null)), table3);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "Body",
                        "CategoryIdentifier",
                        "AuthorIdentifier",
                        "ForumIdentifier",
                        "AuthorDisplayName",
                        "CommentCount"});
            table4.AddRow(new string[] {
                        "Post Title",
                        "Post Body",
                        "11111111-1111-1111-1111-111111111111",
                        "00000000-0000-0000-0000-000000000000",
                        "33333333-3333-3333-3333-333333333333",
                        "Anonymous",
                        "1"});
#line 24
 testRunner.And("the Post has values:", ((string)(null)), table4);
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
